additional_dropout: 0.1
batch_seqlen_test: max
batch_seqlen_test_maxlen: 300
batch_seqlen_test_trim: center
batch_seqlen_train: max
batch_seqlen_train_maxlen: 60
batch_seqlen_train_trim: random
bs: 64
cross_entropy_loss: true
dataset_name: UCF
debug: false
debug_comment: ''
decoder_dropout: 0.1
decoder_hidden_size: 512
distance_fn: L2Loss
embedding_dropout: 0.3
embeddings_batch_norm: true
embeddings_hidden_size: 512
epochs: 50
eval_bs: 64
eval_name: Attention
eval_num_workers: 8
feature_extraction_method: cls_features_non_averaged
input_size_audio: 128
input_size_video: 4096
lr: 7.0e-05
lr_scheduler: true
n_batches: 300
new_model_sequence: true
optimizer: adam
rec_loss: true
reg_loss: true
seed: 42
transformer_depth: 6
transformer_dim: 300
transformer_dim_head: 64
transformer_dropout: 0.3
transformer_embedding_dim: 64
transformer_embedding_dropout: 0.2
transformer_embedding_fourier_scale: 10.0
transformer_embedding_modality: True
transformer_embedding_time_embed_type: sinusoid
transformer_embedding_time_len: 120
transformer_heads: 8
transformer_mlp_dim: 128
transformer_use_class_token: True
transformer_use_embedding_net: true
use_cross_attention: true
use_self_attention: false
verbose: false
selavi: False
zero_shot_split: cls_split
